services:
  ei-video-obj-detection-runner:
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/ai-tracking-camera-with-servo
    environment:
      APP_HOME: /home/arduino/ArduinoApps/ai-tracking-camera-with-servo
      BIND_ADDRESS: 0.0.0.0
      BOARD_NAME: unoq
      CUSTOM_MODEL_PATH: /home/arduino/.arduino-bricks/ei-models
      EI_OBJ_DETECTION_MODEL: /models/ootb/ei/lw-face-det.eim
      EI_V_OBJ_DETECTION_MODEL: /models/ootb/ei/lw-face-det.eim
      HOST_IP: 192.168.0.88
      MODELS_PATH: /var/lib/arduino-app-cli/models
      VIDEO_DEVICE: /dev/video2
      XDG_RUNTIME_DIR: /run/user/1000
